# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d2b1812dccc1598e1c254604b7639a0abf60a4d8f418251a3d9fdd0c690d1ab8ca82aa1d0e9dea0b440e8851387635637879f4269444b8395d3627a9cd5df0b

test:
  secret_key_base: cf514604d6efdf089a3e0ca2b0bea10edd79cfd1d6687bc8694ae7e69d5e5384ab4bce7045cf110326a6552d47f763e488fa4ea07de5e09b408dcba0150b3fe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
